
-- a)
CREATE USER IF NOT EXISTS 'Joao' IDENTIFIED BY 'CHIDTatERMcK';
GRANT SELECT, UPDATE, INSERT, DELETE ON PAGAMENTOS.CADASTRO TO Joao WITH GRANT OPTION;
GRANT SELECT, UPDATE, INSERT, DELETE ON PAGAMENTOS.CLIENTES TO Joao WITH GRANT OPTION;
GRANT SELECT, UPDATE, INSERT, DELETE ON PAGAMENTOS.DESCONTOS TO Joao WITH GRANT OPTION;
GRANT SELECT, UPDATE, INSERT, DELETE ON PAGAMENTOS.EMPREGADOS TO Joao WITH GRANT OPTION;
GRANT SELECT, UPDATE, INSERT, DELETE ON PAGAMENTOS.PAGAMENTOS_ TO Joao WITH GRANT OPTION;
GRANT SELECT ON PAGAMENTOS.vw_funcionario TO Joao WITH GRANT OPTION;
GRANT SELECT ON PAGAMENTOS.vw_salario TO Joao WITH GRANT OPTION;

REVOKE SELECT ON PAGAMENTOS.vw_funcionario FROM Joao;
REVOKE SELECT ON PAGAMENTOS.vw_salario FROM Joao;

-- b)
CREATE USER IF NOT EXISTS 'Maria' IDENTIFIED BY 'MERonaiLEGEr';
GRANT SELECT, UPDATE, INSERT ON PAGAMENTOS.CLIENTES TO Maria;

-- c)
CREATE USER IF NOT EXISTS 'Jose' IDENTIFIED BY 'rpsECeStEISe';
GRANT SELECT ON PAGAMENTOS.CLIENTES TO Jose;
GRANT SELECT ON PAGAMENTOS.DESCONTOS TO Jose;

-- d)
GRANT UPDATE, INSERT, DELETE ON PAGAMENTOS.CLIENTES TO Jose;

-- e)
REVOKE SELECT ON TABLE PAGAMENTOS.CLIENTES FROM Maria;

-- f)
GRANT SELECT, UPDATE, INSERT, DELETE ON PAGAMENTOS.CLIENTES TO Joao WITH GRANT OPTION;
REVOKE SELECT ON TABLE PAGAMENTOS.CLIENTES FROM Joao;
REVOKE UPDATE, INSERT, DELETE ON PAGAMENTOS.CLIENTES FROM Jose;
